# Disable emulator audio
machine:
  environment:
    QEMU_AUDIO_DRV: none

dependencies:
  pre:
    - echo y | android update sdk --no-ui --all --filter "platform,6"
test:
  pre:
    # start emulator
    - emulator -avd circleci-android24 -no-window:
        background: true
        parallel: true
    # wait for emulator to boot
    - circle-android wait-for-boot
    # run tests  against the emulator.
    - ./gradlew connectedAndroidTest
    # copy the build outputs to artifacts
    - cp -r my-project/build/outputs $CIRCLE_ARTIFACTS
    # copy the test results to the test results directory.
    - cp -r my-project/build/outputs/androidTest-results/* $CIRCLE_TEST_REPORTS
