language: android
jdk: oraclejdk8
cache:
  directories:
    - $HOME/.gradle/caches/2.9
    - $HOME/.gradle/daemon
    - $HOME/.gradle/native
    - $HOME/.gradle/wrapper
env:
  global:
    - ANDROID_TARGET=android-15
    - ANDROID_ABI=armeabi-v7a
    - GRADLE_OPTS="-Xmx512m -XX:MaxPermSize=512m"
    - ADB_INSTALL_TIMEOUT=8
android:
  components:
  - tools
  - platform-tools
  - build-tools-25.0.3
  - android-15
  - extra-android-m2repository
  - sys-img-${ANDROID_ABI}-${ANDROID_TARGET}
  #- android-25
script:
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
  - emulator -avd test -noaudio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
  - ./gradlew connectedAndroidTest jacocoTestReport
  # - adb shell setprop dalvik.vm.dexopt-flags v=n,o=v
after_success:
    - pip install --user codecov
    - codecov
    - bash <(curl -s https://codecov.io/bash)
after_failure: "cat $TRAVIS_BUILD_DIR/app/build/outputs/lint-results-debug.xml"
