version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-25-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "castle/build.gradle" }}
      - run:
          name: Accept Licenses
          shell: /bin/bash
          command: eval "yes | sdkmanager --licenses"
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "castle/build.gradle" }}
      - run:
          name: Setup Emulator
          command: sdkmanager "system-images;android-22;default;armeabi-v7a" && echo "no" | avdmanager create avd -n test -k "system-images;android-22;default;armeabi-v7a"
      - run:
          name: Launch Emulator
          command: export LD_LIBRARY_PATH=${ANDROID_HOME}/emulator/lib64:${ANDROID_HOME}/emulator/lib64/qt/lib && emulator64-arm -avd test -noaudio -no-boot-anim -no-window -accel on
          background: true
      - run:
          name: Run Tests
          command: ./gradlew :castle:connectedAndroidTest
      - run:
          name: Run Lint
          command: ./gradlew lint test
      - run:
          name: Run Code Coverage
          command: ./gradlew test createDebugCoverageReport
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results
      - codecov/upload:
          file: app/build/reports/coverage/debug/report.xml
